// <auto-generated />
using System;
using Blazor.News.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.News.Migrations
{
    [DbContext(typeof(NewsDBContext))]
    partial class NewsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsArtikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("HoofdafbeeldingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InhoudEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InhoudNl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OndertitelEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OndertitelNl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PublicatieDatumTijd")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitelEn")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TitelNl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("NieuwsArtikelen");
                });

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NaamEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NaamNl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NieuwsCategorieen");
                });

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsInternalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NieuwsArtikelId")
                        .HasColumnType("int");

                    b.Property<string>("TekstEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TekstNl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("NieuwsArtikelId");

                    b.ToTable("NieuwsInternalLinks");
                });

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsArtikel", b =>
                {
                    b.HasOne("Blazor.News.Data.Models.NieuwsCategorie", "Categorie")
                        .WithMany("NieuwsArtikelen")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsInternalLink", b =>
                {
                    b.HasOne("Blazor.News.Data.Models.NieuwsArtikel", "NieuwsArtikel")
                        .WithMany("InterneLinks")
                        .HasForeignKey("NieuwsArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NieuwsArtikel");
                });

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsArtikel", b =>
                {
                    b.Navigation("InterneLinks");
                });

            modelBuilder.Entity("Blazor.News.Data.Models.NieuwsCategorie", b =>
                {
                    b.Navigation("NieuwsArtikelen");
                });
#pragma warning restore 612, 618
        }
    }
}
